#!/usr/bin/env python3

import subprocess
import os
import time
from tqdm import tqdm

bold = "\033[1m"
blink = "\033[5m"
normal = "\033[0m"
aqua = "\033[36m"
lightred = "\033[91m"
lightgreen = "\033[92m"
lightyellow = "\033[93m"
lightblue = "\033[94m"
lightaqua = "\033[96m"

PROGRAMS = ["tldr", "gedit", "vscode", "w3m", "ranger", "fzf", "neovim", "unzip", "wget", "git", "curl", "docker.io", "docker-compose"]

def install(program):
    program = f"sudo nala install {program} -y"
    subprocess.run(program, shell=True, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)

t = tqdm(PROGRAMS, colour="cyan", initial=1)

for i in t:
    t.set_description(f"{lightaqua}Installing base programs{normal}") 
    install(i)
    print(f"{lightgreen}{i} {lightyellow}successfully installed{normal}")


