#!/usr/bin/env python3

import subprocess
from tqdm import tqdm

GPG_SAVE = "/usr/share/keyrings/brave-browser-archive-keyring.gpg"
GPG_URL = "https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg"
REPO = "deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg] https://brave-browser-apt-release.s3.brave.com/ stable main"
FILE = "/etc/apt/sources.list.d/brave-browser-release.list"

C1 = "sudo apt install -y curl"
C2 = f"sudo curl -fsSLo {GPG_SAVE} {GPG_URL}"
C3 = f"sudo echo {REPO} | sudo tee {FILE}"
C4 = "sudo apt update -y"
C5 = "sudo apt install -y brave-browser"
COMMANDS = [C1, C2, C3, C4, C5]

def SPR(command):
    subprocess.run(command, shell=True, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)

for i in tqdm(COMMANDS, desc="Installing Brave browser", colour="cyan"):
    SPR(i)
print("Brave browser successfully installed!")
