#!/bin/bash

tclear="tput sgr0" 
tred="tput setaf 1"
tgreen="tput setaf 2"
torange="tput setaf 3"
tblue="tput setaf 4"
tpurple="tput setaf 5"
tcyan="tput setaf 6"
tlightgrey="tput setaf 7"
tgrey="tput setaf 8" 
tlightred="tput setaf 9"
tlightgreen="tput setaf 10"
tlightorange="tput setaf 11"
tlightblue="tput setaf 12"
tlightpurple="tput setaf 13"
tlightcyan="tput setaf 14"
twhite="tput setaf 15"








clear

printf "

 ██████╗██╗  ██╗███████╗ █████╗ ████████╗
██╔════╝██║  ██║██╔════╝██╔══██╗╚══██╔══╝
██║     ███████║█████╗  ███████║   ██║   
██║     ██╔══██║██╔══╝  ██╔══██║   ██║   
╚██████╗██║  ██║███████╗██║  ██║   ██║   
 ╚═════╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝   ╚═╝   
------------------------------------------------
\n\n"
$tgreen
sleep 1
printf "Didn't your momma tell you it's bad to cheat...\n\n"
sleep 2
$tclear
$tcyan
printf "Are you sure you want to cheat???\n\n"
sleep 2
$tclear
$twhite
printf "[Yes|no]: "
$tclear
$tcyan
read -r response
response=$(echo "$response" | tr "[:upper:]" "[:lower:]" | cut -c 1)

while [ "$response" != "y" ] && [ "$response" != "" ] &&
[ "$response" != "n" ]; do

	$tclear
	$tlightgreen
	sleep 1
	printf "\nPlease enter a valid response\n\n" 
	$tclear
	$twhite
	sleep 1
	printf "[Yes|no]: "
	$tclear
	read -r response
	response=$(echo "$response" | tr "[:upper:]" "[:lower:]" | cut -c 1)

done

if
	[ "$response" == "n" ]
then
	$tclear
	$tlightred
	printf "\nAborting installation...\n\n"
	sleep 2
	exit 2
else
	if cheat > /dev/null; then
		$tclear
		$torange
		printf "\n\nCheat is already installed on your system\n\n"
		sleep 2
		$tlightred
		printf "Aborting installation...\n\n"
		sleep 2
		exit
	else 
		$tclear
		$tlightpurple
		printf "Getting things ready...\n\n"
	fi
fi
	
cd ~/cheattemp
wget https://github.com/cheat/cheat/releases/download/4.4.0/cheat-linux-amd64.gz
gunzip cheat-linux-amd64.gz
chmod +x cheat-linux-amd64
sudo mv cheat-linux-amd64 /usr/local/bin/cheat
rm -rf ~/cheattemp
$tclear
$tlightblue
printf "cheat was successfully installed \n\n"
sleep 2
$tclear
$tgreen
printf "press ENTER to close the installer..."
$tclear
read -r  
exit 0
