#!/usr/bin/env python3

import os
import subprocess
import time
from tqdm import tqdm

APPEND = """
  # fnm
  export PATH="$HOME/.local/share/fnm:$PATH"
  eval "`fnm env`"

"""

C1 = "curl -fsSL https://fnm.vercel.app/install | bash"
C2 = f"sudo echo {APPEND} >> ~/.bashrc"
C3 = "source ~/.bashrc" 
COMMANDS = [C1, C2, C3]

def SPR(command):
    subprocess.run(command, shell=True, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)

t = tqdm(COMMANDS, colour="cyan", desc="Installing FNM")

for i in t:
    SPR(i)
    time.sleep(.5)
