#!/bin/bash

echo "YOU MUST RUN THIS AS SUDO!!"
echo "IF YOU ARE NOT RUNNING SUDO EXIT NOW"

git clone https://github.com/CodingRanjith/hackingtoolkit.git

chmod +x hackingtoolkit

cd hackingtoolkit

sudo python3 htk.py
