#!/usr/bin/env python3

import subprocess
import time
import os
from tqdm import tqdm

PROGRAMS = ["cheat", "brave_browser", "fnm", "miniconda", "nerd_font -f VictorMono"]

def install(program):
    subprocess.run(program, shell=True)

t = tqdm(PROGRAMS, colour="cyan")

os.system("clear")
print("Starting main install")
for i in t:
    t.set_description(desc=f"Installing {i}")
    time.sleep(3)
    i = f"./{i}"
    install(i)
    time.sleep(3)
