#!/usr/bin/env python3

import subprocess
import time
import os
from tqdm import tqdm

PROGRAMS = ["cheat", "brave_browser", "fnm", "miniconda", "nerd_font -f VictorMono"]

def install(program):
    subprocess.run(f"./{program}", shell=True)

t = tqdm(PROGRAMS, colour="cyan", desc="Installing main programs")

os.system("clear")
print("Starting main install")
for i in t:
    install(i)
    time.sleep(3)
