#!/usr/bin/env python3

import subprocess
import os
import time
from tqdm import tqdm

C1 = "mkdir -p ~/miniconda3"
C2 = "wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda3/miniconda.sh"
C3 = "bash ~/miniconda3/miniconda.sh -b -u -p ~/miniconda3"
C4 = "rm -rf ~/miniconda3/miniconda.sh"
C5 = "~/miniconda3/bin/conda init bash"
C6 = "~/miniconda3/bin/conda init zsh"

COMMANDS = [C1, C2, C3, C4, C5, C6]

def sp(command):
    subprocess.run(command, shell=True, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL) 
os.system("clear")
for i in tqdm(COMMANDS, desc = "Installing miniconda"):
    sp(i)

print("miniconda successfully installed!")

